### PR TITLE
Migrate to SMAPI 4.0 & Add auto-updates for nuget packages

### PR DESCRIPTION
**Pull request by TSRBerry**
This PR solves all deprecation warnings for SMAPI 4.0, adds auto-updates to nuget packages and improves the code formatting.

Code formatting was automatically done by vscode, but if you don't like that I'll revert that.

I updated SMAPI to the latest version and created a workflow to automatically merge any future updates after confirming the project still succeeds to build.

Migration was done by using the [wiki page](https://stardewvalleywiki.com/Modding:Migrate_to_SMAPI_4.0) as a reference and adjusting the code accordingly.

I plan on contributing another feature, but wanted to make sure the project builds without any warnings/errors first, which is how this PR came to be.

### CODE REVIEW

**Comment by JoeStrout** [comment]
Please revert the code formatting.  The default VS code formatting is very wrong in my opinion (in several ways).

**Comment by TSRBerry** [comment]
Will do that!

Is there a way to enforce the code formatting you want? (Would `.editorconfig` do that?)

**Comment by JoeStrout** [comment]
I don't believe there is any .editorconfig that works between the Mac version of Visual Studio (which I use) and the Windows version, or with VSCode.  I'd be delighted to be wrong about that, however.

Here's the format overview in preferences:
image

...and of course, indent with tabs rather than spaces.

**Comment by TSRBerry** [comment]
What do you think of this?
I only kept the rules that were modified, but hopefully this catches everything shown in the screenshot.
There are many more options, so I just left a link to the reference pages in the file.

**Comment by JoeStrout** [comment]
Looks promising!  I'm not sure which IDEs will actually pay any attention to it, but it certainly can't hurt.

**Comment by JoeStrout** [comment]
So the PR is looking much better.  I still see a lot of "noise" changes in the whitespace.  Maybe some of that is unavoidable, but can we do anything about the common case of blank lines:
image

Here the original code had whitespace up to the proper indentation level for that block of code; your version strips that out.  That makes it harder to review the actual code changes in the PR, and also makes it slightly harder for a user who comes along later and wants to insert some code on the blank line.  Sure, if they hit return the editor ought to insert the proper indentation, but what if they want to type something and _then_ hit Return?  They have to first mash the Tab key to get the cursor where it belongs.

So if there is some way in your editor to make it not strip the whitespace out of blank lines, I'd much prefer it.

**Comment by TSRBerry** [comment]
Oh I think there was an option for that in `.editorconfig` as well. I'll fix that and rebase again!

**Comment by TSRBerry** [comment]
Should be a lot better now!

**Comment by JoeStrout** [comment]
Yeah looks good!  I'm going to study this more carefully and likely merge it in tomorrow.  Thank you for your contribution!

**Comment by JoeStrout** [comment]
Nice work.  I hope the thing you're gearing up to tackle next is https://app.bountysource.com/issues/111311010-feature-add-multiplayer-support-to-farmtronics-sdv-mod — you would be a hero to a whole lot of Farmtronics users!

Also, feel free to hop into our Discord server (link at bottom of https://miniscript.org), or DM me directly there, so we can communicate more quickly as you tackle such a complex issue.

**Pull request merged**
